---
title: "Mini Poster"
author: "Arif Waghbakriwala"
date: "10/5/2021"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


GDP per capita (Single graph)
```{r}
library(ggplot2)
library(WDI)
library(scales)

df<-WDI(
  country = c("USA","CAN","CHN","IND","PAK","DEU","DNK","NOR","SWE","FIN","ISL"),
  indicator = c("NY.GDP.PCAP.CD","NY.GDP.MKTP.CD"),
  start = 1960,
  end = 2020,
  extra = FALSE,
  cache = NULL,
  latest = NULL,
  language = "en"
)

names(df) <- c('code', 'country', 'year', 'GDP_Per_Cap','GDP_Annual')
plt <- ggplot(df, aes(x=year,GDP_Per_Cap,color=country))+
    geom_smooth(stat='identity',size=0.2,bins = 1)+
  scale_y_continuous(labe = dollar)+
  scale_x_continuous(breaks = round(seq(min(df$year), max(df$year), by = 2),1)) +
  theme(axis.text.x= element_text(angle = 90, vjust = 0.5, hjust=1))+
  ggtitle("GDP Per Capita (1960-2020)")
plt

```
GDP per capita (Faceted)
```{r}
library(ggplot2)
library(WDI)
library(scales)

df<-WDI(
  country = c("USA","CAN","CHN","IND","PAK","DEU","DNK","NOR","SWE","FIN","ISL"),
  indicator = c("NY.GDP.PCAP.CD","NY.GDP.MKTP.CD"),
  start = 1960,
  end = 2020,
  extra = FALSE,
  cache = NULL,
  latest = NULL,
  language = "en"
)

names(df) <- c('code', 'country', 'year', 'GDP_Per_Cap','GDP_Annual')
plt <- ggplot(df, aes(x=year,GDP_Per_Cap,color=country))+
    geom_smooth(stat='identity',size=0.2,bins = 1)+
  scale_y_continuous(labe = dollar)+
  theme(axis.text.x= element_text(angle = 90, vjust = 0.5, hjust=1))+
  facet_wrap(~country)+
  ggtitle("GDP Per Capita - Faceted (1960-2020)")
plt

```
GDP Annual (Single Graph)
```{r}
library(ggplot2)
library(WDI)
library(scales)

df<-WDI(
  country = c("USA","CAN","CHN","IND","PAK","DEU","DNK","NOR","SWE","FIN","ISL"),
  indicator = c("NY.GDP.PCAP.CD","NY.GDP.MKTP.CD"),
  start = 1960,
  end = 2020,
  extra = FALSE,
  cache = NULL,
  latest = NULL,
  language = "en"
)

names(df) <- c('code', 'country', 'year', 'GDP_Per_Cap','GDP_Annual')

plt1 <- ggplot(df, aes(x=year,GDP_Annual,color=country))+
    geom_smooth(stat='identity',size=0.2)+
  scale_y_continuous(labe = dollar)+
  scale_x_continuous(breaks = round(seq(min(df$year), max(df$year), by = 2),1)) +
  theme(axis.text.x= element_text(angle = 90, vjust = 0.5, hjust=1))+
  ggtitle("Annual GDP (1960-2020)")
plt1
```

GDP Annual (Faceted)
```{r}
library(ggplot2)
library(WDI)
library(scales)

df<-WDI(
  country = c("USA","CAN","CHN","IND","PAK","DEU","DNK","NOR","SWE","FIN","ISL"),
  indicator = c("NY.GDP.PCAP.CD","NY.GDP.MKTP.CD"),
  start = 1960,
  end = 2010,
  extra = FALSE,
  cache = NULL,
  latest = NULL,
  language = "en"
)

names(df) <- c('code', 'country', 'year', 'GDP_Per_Cap','GDP_Annual')

plt1 <- ggplot(df, aes(x=year,GDP_Annual,color=country))+
    geom_smooth(stat='identity',size=0.2)+
  scale_y_continuous(labe = dollar)+
  #scale_x_continuous(breaks = round(seq(min(df$year), max(df$year), by = 2),1)) +
  theme(axis.text.x= element_text(angle = 90, vjust = 0.5, hjust=1))+
  facet_wrap(~country)
plt1
```









